name: Daily PERM Status Check

on:
  schedule:
    - cron: '0 6 * * *'   # Runs at 6:00 AM CST
    - cron: '0 10 * * *'  # Runs at 10:00 AM CST
    - cron: '0 14 * * *'  # Runs at 2:00 PM CST
    - cron: '0 18 * * *'  # Runs at 6:00 PM CST
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Runs on every push to main branch

jobs:
  current_perm_status:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          npm install @badeball/cypress-cucumber-preprocessor @bahmutov/cypress-esbuild-preprocessor
          
      - name: Create Cypress directories
        run: |
          mkdir -p cypress/videos
          mkdir -p cypress/screenshots
        
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/features/perm-status.feature"
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots 