name: Daily Perm Status Check

on:
  schedule:
    - cron: '0 15 * * *'  # 9 AM CST
    - cron: '0 19 * * *'  # 1 PM CST
    - cron: '0 0 * * *'   # 6 PM CST
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Runs on every push to main branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install cypress @badeball/cypress-cucumber-preprocessor @bahmutov/cypress-esbuild-preprocessor
        
      - name: Create Cypress directories
        run: |
          mkdir -p cypress/videos
          mkdir -p cypress/screenshots
          mkdir -p cypress/results
        
      - name: Run Cypress tests
        run: |
          npx cypress run --spec "cypress/e2e/features/perm-status.feature" || true
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
        
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/results
          retention-days: 7 